---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Run Actionlint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/**'
  push:
    paths:
      - '.github/**'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Check workflows
        uses: docker://rhysd/actionlint:1.7.7
        with:
          args: -color
