name: Regenerate parser

on:
  workflow_dispatch:
  # disable until automation / permissions are setup
  # pull_request:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  regenerate:
    uses: tree-sitter/workflows/.github/workflows/regenerate.yml@main
    if: github.actor == 'dependabot[bot]'
    with:
      abi-version: "14"
